# Generated by Django 6.1 on 2026-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='JTC Logo', null=True, upload_to='site/')),
                ('carnival_name', models.CharField(default='SJIS Inter-School Tech Carnival 2026', max_length=200)),
                ('carnival_start_date', models.DateField(blank=True, null=True)),
                ('carnival_end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(default='St. Joseph International School, 97 Asad Avenue, Mohammadpur, Dhaka 1207', max_length=300)),
                ('tagline', models.CharField(default='Where Innovation Meets Excellence', max_length=300)),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(default='jtc@sjis.edu.bd', max_length=254)),
                ('contact_phone', models.CharField(default='+880 2-9116271', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('announcement_banner', models.TextField(blank=True, help_text='Scrolling announcement text (leave blank to hide)')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_user', models.CharField(blank=True, max_length=100)),
                ('sms_pass', models.CharField(blank=True, max_length=100)),
                ('sms_from', models.CharField(blank=True, default='JTCSJIS', max_length=20)),
                ('email_confirmation_enabled', models.BooleanField(default=True)),
                ('email_from_name', models.CharField(default='Josephite Tech Club', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
