# Generated by Django 6.1 on 2026-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, help_text='Registration opening date and time', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='carnival_end_date',
            field=models.DateField(blank=True, help_text='Carnival end date (e.g. 2026-10-02)', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='carnival_start_date',
            field=models.DateField(blank=True, help_text='Carnival start date (e.g. 2026-10-01)', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Registration closing deadline date and time', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_open',
            field=models.BooleanField(default=True, help_text='Master toggle to allow or disable registrations'),
        ),
    ]
