# Generated by Django 5.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_registration_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_enabled',
            field=models.BooleanField(default=True, help_text='Enable SSLCommerz instant card/bKash/Nagad gateway'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_store_id',
            field=models.CharField(blank=True, help_text='Merchant Store ID from SSLCommerz', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_store_pass',
            field=models.CharField(blank=True, help_text='Store Password / Secret Key', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_is_sandbox',
            field=models.BooleanField(default=False, help_text='Checked for Sandbox/Test mode, unchecked for Live production'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+880 2-9116271', help_text='Helpline numbers displayed in footer and passes', max_length=100),
        ),
    ]
