# Generated by Django on 2026-09-13
from django.db import migrations


def sync_universities(apps, schema_editor):
    School = apps.get_model('core', 'School')

    universities = [
        ('University of Dhaka', 'DU', 15),
        ('Bangladesh University of Engineering and Technology', 'BUET', 16),
        ('Islamic University of Technology', 'IUT', 17),
        ('BRAC University', 'BRACU', 18),
        ('North South University', 'NSU', 19),
        ('Independent University Bangladesh', 'IUB', 20),
        ('East West University', 'EWU', 21),
        ('American International University - Bangladesh', 'AIUB', 22),
        ('United International University', 'UIU', 23),
        ('Northern University Bangladesh', 'NUB', 24),
    ]

    for name, short_name, order in universities:
        sch = School.objects.filter(short_name=short_name).first() or School.objects.filter(name=name).first()
        if sch:
            sch.name = name
            sch.short_name = short_name
            sch.order = order
            sch.is_active = True
            sch.save()
        else:
            School.objects.create(
                name=name,
                short_name=short_name,
                order=order,
                is_active=True
            )


def reverse_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_sslcommerz_enabled_and_more'),
    ]

    operations = [
        migrations.RunPython(sync_universities, reverse_code=reverse_sync),
    ]
