# Generated by Django 5.0.14 on 2026-09-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_external_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Enable automated daily cart reminder emails for pending registrations'),
        ),
    ]
