# Generated by Django 5.0.14 on 2026-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_participant_email_alter_participant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bundle_bonus_fc',
            field=models.BooleanField(default=False, help_text='Participant is entitled to one free FC Game Zone round (bundle bonus)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='True if this is a Bundle Competition Package registration (৳1,000 flat)'),
        ),
    ]
