# Generated by Django 5.0.14 on 2026-09-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_bundle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last cart reminder email sent', null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of cart reminder emails sent'),
        ),
    ]
