# Generated by Django 6.1 on 2026-09-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('AI', 'AI & Tech'), ('CODING', 'Coding'), ('DIGITAL_ART', 'Digital Art & Media'), ('GAMING', 'Gaming'), ('ESPORTS', 'E-Sports'), ('ROBOTICS', 'Robotics & Drone'), ('QUIZ', 'Quiz & Knowledge'), ('CREATIVE', 'Creative'), ('TYPING', 'Typing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True, help_text='Detailed rules in markdown format')),
                ('judging_criteria', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('BOTH', 'Individual or Team')], default='INDIVIDUAL', max_length=10)),
                ('individual_fee', models.PositiveIntegerField(default=0, help_text='Fee in BDT')),
                ('team_fee', models.PositiveIntegerField(default=0, help_text='Team fee in BDT (if team)')),
                ('team_min', models.PositiveIntegerField(default=1)),
                ('team_max', models.PositiveIntegerField(default=1)),
                ('submission_type', models.CharField(choices=[('ONLINE', 'Online (during event)'), ('PENDRIVE', 'Pendrive / Offline'), ('STAGE', 'Stage Presentation'), ('LAB', 'Computer Lab'), ('PHYSICAL', 'Physical Submission'), ('MIXED', 'Mixed')], default='ONLINE', max_length=10)),
                ('venue_detail', models.CharField(blank=True, help_text='e.g. Computer Lab, Old Building Room X', max_length=200)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('highlight', models.BooleanField(default=False, help_text='Show as featured event on home page')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Group A — Grade 3–4'), ('B', 'Group B — Grade 5–6'), ('C', 'Group C — Grade 7–8'), ('D', 'Group D — Grade 9–A2 (Grade 12)'), ('E', 'Group E — University (Bachelors 1st–4th year)')], max_length=1, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('grade_range', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EventFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='eligibility_groups',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventgroup'),
        ),
    ]
