# Generated by Django on 2026-09-14
from django.db import migrations


def update_line_robot_groups(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    EventGroup = apps.get_model('events', 'EventGroup')

    # Ensure Group E exists
    group_e, _ = EventGroup.objects.get_or_create(
        code='E',
        defaults={
            'label': 'Group E — University (Bachelors 1st–4th year)',
            'grade_range': 'University Level',
        }
    )

    # Find Line Robot event
    event = Event.objects.filter(slug='line-robot').first()
    if event:
        # Ensure Groups A to E are all attached
        for code in ['A', 'B', 'C', 'D']:
            grp = EventGroup.objects.filter(code=code).first()
            if grp:
                event.eligibility_groups.add(grp)
        event.eligibility_groups.add(group_e)

        # Update rules text if present
        if event.rules:
            event.rules = event.rules.replace(
                "Grade 3 to 12 (Group A to Group D)",
                "Grade 3 to 12 & University Level (Group A to Group E)"
            ).replace(
                "Grade 3 to 12 (Group A to D)",
                "Grade 3 to 12 & University Level (Group A to E)"
            )
            event.save()


def reverse_line_robot_groups(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    EventGroup = apps.get_model('events', 'EventGroup')
    group_e = EventGroup.objects.filter(code='E').first()
    event = Event.objects.filter(slug='line-robot').first()
    if event and group_e:
        event.eligibility_groups.remove(group_e)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_line_robot_groups, reverse_code=reverse_line_robot_groups),
    ]
