# Generated by Django on 2026-09-29
from django.db import migrations


def update_robo_showcase_groups(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    EventGroup = apps.get_model('events', 'EventGroup')

    # Find Robo Showcase event
    event = Event.objects.filter(slug='robo-showcase').first()
    if event:
        # Ensure Groups A, B, C, D, E are attached
        for code in ['A', 'B', 'C', 'D', 'E']:
            grp = EventGroup.objects.filter(code=code).first()
            if grp:
                event.eligibility_groups.add(grp)

        # Update rules text if present
        if event.rules:
            event.rules = event.rules.replace(
                "- Group C, D, E (Grade 7 to University 4th Year)",
                "- Group A, B, C, D, E (Grade 3 to University 4th Year)"
            ).replace(
                "Group C, D, E",
                "Group A, B, C, D, E"
            )
            event.save()


def reverse_robo_showcase_groups(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    EventGroup = apps.get_model('events', 'EventGroup')
    event = Event.objects.filter(slug='robo-showcase').first()
    if event:
        for code in ['A', 'B']:
            grp = EventGroup.objects.filter(code=code).first()
            if grp:
                event.eligibility_groups.remove(grp)
        if event.rules:
            event.rules = event.rules.replace(
                "- Group A, B, C, D, E (Grade 3 to University 4th Year)",
                "- Group C, D, E (Grade 7 to University 4th Year)"
            )
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_update_line_robot_groups'),
    ]

    operations = [
        migrations.RunPython(update_robo_showcase_groups, reverse_code=reverse_robo_showcase_groups),
    ]
