# Generated by Django 5.0.14 on 2026-09-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('VERIFIER', 'Payment Verifier'), ('VIEWER', 'Viewer (Read-only)')], default='ADMIN', max_length=20),
        ),
    ]
